name: Hired Guns Creative
favicon: null
layout_spectrum: 0.529058649437502
typography_spectrum: 0.035434883553534746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9648391597438604
  lightness: 0.8674449557438493
  saturation: 0.057911216048523784
  rhythmicContrast: 0.3037562945391983
purpose: []
